# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bottom',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
